language: cpp
compiler: gcc

before_install:
  # from the tutorial https://arne-mertz.de/2017/04/continuous-integration-travis-ci/
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt install -qq cppcheck

before_script:
  - mkdir build
  - cd build

script:
  - cmake ..
  - make
  - ./hello
  - ./divide 42 0
  - cppcheck --quiet --error-exitcode=1 .
